version: "3.9"
services:
  nginx:
    image: openkilt/openrepo:latest
    command: nginx
    restart: unless-stopped
    ports:
      - "7376:8080"
    depends_on:
      - "django"
    volumes:
      - ./openrepo-data:/var/lib/openrepo



  django:
    image: openkilt/openrepo:latest
    expose:
      - "8000"
    command: run_openrepoweb
    restart: unless-stopped
    volumes:
      - ./openrepo-data:/var/lib/openrepo
    environment:
      - OPENREPO_DB_TYPE=postgresql
      - OPENREPO_PG_DATABASE=openrepo
      - OPENREPO_PG_USERNAME=postgres
      - OPENREPO_PG_PASSWORD=postgres
      - OPENREPO_PG_HOSTNAME=db
    depends_on:
      - "db"


  worker:
    image: openkilt/openrepo:latest
    command: ./django/manage.py runworker
    volumes:
      - ./openrepo-data:/var/lib/openrepo
    restart: unless-stopped
    environment:
      - OPENREPO_DB_TYPE=postgresql
      - OPENREPO_PG_DATABASE=openrepo
      - OPENREPO_PG_USERNAME=postgres
      - OPENREPO_PG_PASSWORD=postgres
      - OPENREPO_PG_HOSTNAME=db
    depends_on:
      - "django"


  db:
    image: postgres:16.3-alpine3.20
    expose:
      - "5432"
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=openrepo
    volumes:
      - ./openrepo-data/postgres:/var/lib/postgresql/data
